### ISSUE TITLE
The global search for new documents in nuxt3 has not been done to prevent shaking

### ISSUE THREAD

**Issue by mark980828** [nuxt/nuxt.com#1396] opened 2023-10-24 08:59 UTC
### Environment

---

### Reproduction

https://nuxt.com

### Describe the bug

The global search for new documents in nuxt3 has not been done to prevent shaking

**Comment by benjamincanac** [comment] 2023-10-24 16:37
Could you elaborate on this? Not sure to understand the issue here.

**Comment by mark980828** [comment] 2023-10-25 11:19
> Could you elaborate on this? Not sure to understand the issue here.

Continuous input will get stuck during global search.

**Comment by benjamincanac** [comment] 2023-11-04 11:45
This should have been fixed with the latest `@nuxt/ui-pro` release. Let me know if you still encounter the issue!

**Closed** 2023-11-04 11:44 UTC
Labels: question

**Comment by mark980828** [comment] 2023-11-05 09:22
> 最新版本应该已修复此问题`@nuxt/ui-pro`。如果您仍然遇到该问题，请告诉我！

This problem seems to have not been completely resolved.

https://github.com/nuxt/nuxt.com/assets/36203842/97a612ea-5096-499f-9849-32ff5a470e6a

**Comment by benjamincanac** [comment] 2023-11-05 10:01
I really can't reproduce this as it's all smooth on my end, what browser are you using?

**Comment by mark980828** [comment] 2023-11-05 10:17
> I really can't reproduce this as it's all smooth on my end, what browser are you using? https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_11_05_at_11_03_27_f89294b8ef.mp4

You can press 1 and don't loosen it.
I am using Chrome/118.0.0.
