### ISSUE TITLE
nuxt.com broken...

### ISSUE THREAD

**Issue by CHEWX** [nuxt/nuxt.com#1383] opened 2023-10-18 21:03 UTC
### Environment

NA

### Reproduction

Click getting started, then refresh the page, it 404s...

### Describe the bug

404 on page refresh of non home page

Video below...

https://iframe.mediadelivery.net/play/161467/0943c0ad-fa76-40f5-8fa5-ceabd7ef0e1a

**Comment by benjamincanac** [comment] 2023-10-23 12:54
I haven't been able to reproduce this, do you still encounter issues on refresh?

@CHEWX There is an open issue for this page resulting in 404: #1391

**Comment by CHEWX** [comment] 2023-10-23 13:39
@benjamincanac 

https://github.com/nuxt/nuxt.com/issues/1383#issuecomment-1770833841

This still doesn't work, tried incognito too.

**Comment by benjamincanac** [comment] 2023-10-23 13:41
@CHEWX This should be fixed soon, the issue is still open.

**Closed** 2023-10-25 09:34 UTC
Labels: documentation

**Comment by CHEWX** [comment] 2023-10-26 08:31
Why is this closed @Atinux - not planning on fixing it?

**Comment by Atinux** [comment] 2023-10-27 11:23
I cannot reproduce it

**Comment by CHEWX** [comment] 2023-10-27 12:09
Strange, still broken here, just getting too many redirects on that page.

Both on wifi and 4g and in incognito mode and not to avoid and specific issues on my end.

Oh well, just flagging.

**Comment by huang-julien** [comment] 2023-10-27 12:11
clearing the cache works for me but this has been fixed on nuxt edge
