### ISSUE TITLE
500 error loading dynamically imported module on Firefox

### ISSUE THREAD

**Issue by Akryum** [nuxt/nuxt.com#1569] opened 2024-04-23 15:06 UTC
Going to any docs page (such as [this one](https://nuxt.com/docs/getting-started/introduction)) shows an Error 500 on Firefox:

![image](https://github.com/nuxt/nuxt.com/assets/2798204/b68588ba-603d-476f-a841-5410abbf7683)

Disable strict protections and ad blocking extensions doesn't help.

**Comment by pmnzt** [comment] 2024-04-23 18:08
Me too
![image](https://github.com/nuxt/nuxt.com/assets/94640870/f424c069-abed-4be9-a338-d870dcad9d70)

**Comment by manniL** [comment] 2024-04-25 16:02
Weirdly I can't reproduce this in my FF dev edition. We have some ideas to check though.
<img width="1711" alt="image" src="https://github.com/nuxt/nuxt.com/assets/640208/5e83dfcc-d4f7-4054-8671-06e699a33b5f">

**Comment by whiterqbbit** [comment] 2024-04-25 16:14
> We purged the CF cache. Does it work again for you?

It does work now ! Thanks.

**Comment by sajadhsm** [comment] 2024-05-01 19:22
It's happening on Chrome and Safari for me. Firefox is fine though!

Chrome:
<img width="1494" alt="image" src="https://github.com/nuxt/nuxt.com/assets/20022818/ef472517-e831-4af9-b0af-d4f794361ed6">

Safari:
<img width="1308" alt="image" src="https://github.com/nuxt/nuxt.com/assets/20022818/8c19efdc-56ba-4351-a922-e23446bb3c2e">

**Comment by manniL** [comment] 2024-05-02 06:53
@sajadhsm could you attach a HAR?

**Comment by sajadhsm** [comment] 2024-05-02 14:26
@manniL It's fixed now. I'll attach a HAR file if it happens next time.

**Comment by manniL** [comment] 2024-05-07 14:33
@YUN-RU-TSENG could you send a HAR file by any chance?

**Comment by YUN-RU-TSENG** [comment] 2024-05-07 15:09
@manniL thx ~ It's work now, but don't know why.

 I'll send the HAR file if it happens.

**Comment by danielroe** [comment] 2024-05-10 10:26
For what it's worth, the file in the most recent screenshot (in #1580) that's giving a 404 is working for me. We think it's a Cloudflare issue - they are caching a 404 for these static assets, which is probably a result of them not being available at some point in the Vercel deployment process.

The reason this has started occurring is that we recently switched on Cloudflare in order to work around an issue with Vercel's network not being accessible in some networks (likely a regional ISP issue).

**Comment by noook** [comment] 2024-05-10 10:27
Github doesn't accept HAR files, so here it is uploaded to file.io

https://file.io/FMN3wpkD2WZU

**Comment by mlgarchery** [comment] 2024-05-10 11:04
Still having this issue, anywhere in the doc 
![image](https://github.com/nuxt/nuxt.com/assets/16239564/c68010b1-ac49-4107-b64e-d515e4979b9e)

**Comment by v0id-4lpz** [comment] 2024-05-10 13:49
Posted my HAR on https://github.com/nuxt/nuxt.com/issues/1580#issuecomment-2104515794

**Closed** 2024-09-05 03:28 UTC
